name: Sync to Template Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo (wallsite)
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Destination Repo (wallsite-template)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/wallsite-template
          token: ${{ secrets.REPO_ACCESS_TOKEN }} # A PAT is required
          path: destination

      - name: Sync files from source to destination
        run: |
          # Copy all files, deleting ones that no longer exist in source
          # Crucially, exclude the src and .git directories
          rsync -av --delete --exclude='/src/' --exclude='.git/' source/ destination/

      - name: Commit and push changes
        run: |
          cd destination
          if [[ -z $(git status -s) ]]; then
            echo "No changes to sync."
            exit 0
          fi
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "ci: sync from main repository"
          git push
